import Layout from '@/components/Layout'
import Head from 'next/head'
import profilePic from "../../public/images/profile/Frieren_is_learning_React.jpg"
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect />

      <main className='flex items-center w-full min-h-screen 
      bg-backgroundLight text-textPrimaryLight
      dark:bg-background dark:text-textPrimary'>

        {/* 
        sizes attribute under priority for profilepic image makes profile picture look small
        on the iPhone Pro 12 and iPhone 14 Pro Max

         sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
         */}
        <Layout className="pt-0 max-md:p-16 max-sm:pt-8">
          {/* gap-16 */}
          <div className="flex items-center justify-between w-full max-lg:flex-col gap-16 max-md:gap-8"> 
            {/* className="flex-1 max-w-md" */}
            {/* className="w-1/2 max-md:w-full" */}
            <div className="flex-1 max-w-md"> 
              <Image 
                src={profilePic} 
                alt="Portfolio Website Main Cover Image" 
                className="w-full h-auto rounded-2xl max-lg:hidden max-md:inline-block max-md:w-full"
                priority
              />
            </div>
            {/* flex-[1.5] flex flex-col items-start justify-center */}
            {/* w-1/2 flex flex-col items-center self-center max-lg:w-full max-lg:text-center */}
            <div className="flex-[1.5] flex flex-col items-start justify-center max-lg:w-full max-lg:text-center">

              <AnimatedText 
                text="Building Scalable Software Across Systems, Web, and Games." 
                className="!text-6xl !text-left max-xl:!text-5xl max-lg:!text-center max-lg:!text-6xl max-md:!text-5xl max-sm:!text-3xl"
              />

              <p className="my-4 text-base font-medium 
              text-textSecondaryLight dark:text-textSecondary
              max-md:text-sm max-sm:text-xs">
                Greetings! I&apos;m <span className="font-bold">Vaibhav Saini</span>, a <span className="text-primary dark:text-primaryDark">software developer </span>
                with a <span className="text-primary dark:text-primaryDark">strong computer science foundation</span>, experienced in everything from 
                <span className="text-primary dark:text-primaryDark"> low-level systems programming in C </span> to 
                <span className="text-primary dark:text-primaryDark"> full-stack web development</span> and <span className="text-primary dark:text-primaryDark">game development</span>. 
                I focus on understanding core concepts so I can quickly adapt, learn new technologies, and build effective solutions, regardless of the stack.
              </p>

              <div className="flex items-center self-start mt-2 max-lg:self-center">
                {/* Bouncing Button Animation */}
                {/* animate-bounce focus:animate-none hover:animate-none
                  tracking-wide */}
                <Link 
                  href="/resume.pdf" 
                  target={"_blank"}
                  className="flex items-center 
                  bg-accent text-light 
                  p-2.5 px-6 rounded-lg text-lg font-semibold
                  hover:bg-accentSoft hover:text-dark
                  border-2 border-transparent
                  hover:border-accent
                  max-md:p-2 max-md:px-4 max-md:text-base
                  transition-all
                  "
                  download={true}
                >
                  Resume <LinkArrow className={"w-6 ml-1"} />
                </Link>

                <Link 
                  href="mailto:vaibhav.saini.professional@proton.me" 
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize 
                  text-accent underline
                  hover:text-accentSoft
                  transition-colors
                  max-md:text-base"
                >
                  Contact
                </Link>

              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
    </>
  )
}