import Layout from '@/components/Layout'
import Head from 'next/head'
import profilePic from "../../public/images/profile/Frieren_Transparent.png"
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'
export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio | Home Page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className="pt-0 max-md:p-16 max-sm:pt-8">
          {/* gap-16 */}
          <div className="flex items-center justify-between w-full max-lg:flex-col gap-16 max-md:gap-8"> 
            {/* className="flex-1 max-w-md" */}
            {/* className="w-1/2 max-md:w-full" */}
            <div className="flex-1 max-w-md"> 
              <Image src={profilePic} alt="Portfolio Website Main Cover Image" className="w-full h-auto rounded-2xl max-lg:hidden max-md:inline-block max-md:w-full"
                priority
                sizes="(max-width: 768px) 100vw,
                      (max-width: 1200px) 50vw,
                      50vw"
              />
            </div>
            {/* flex-[1.5] flex flex-col items-start justify-center */}
            {/* w-1/2 flex flex-col items-center self-center max-lg:w-full max-lg:text-center */}
            <div className="flex-[1.5] flex flex-col items-start justify-center max-lg:w-full max-lg:text-center">
              {/* ! overrides classes. 
                Example: !text-6xl overrides text-8xl in AnimatedText.js */}
              <AnimatedText text="Building Scalable Software Across Systems, Web, and Games." className="text-6xl! text-left!
              max-xl:text-5xl! max-lg:text-center! max-lg:text-6xl! max-md:text-5xl! max-sm:text-3xl!
              " />
              <p className="my-4 text-base font-medium max-md:text-sm max-sm:text-xs">
                I’m a software developer with a strong computer science foundation, experienced in everything from low-level systems programming
                in C to full-stack web development and game development. I focus on understanding core concepts so I can quickly adapt, learn new technologies,
                and build effective solutions, regardless of the stack.
              </p>
              <div className="flex items-center self-start mt-2 max-lg:self-center">
                <Link href="/resume.pdf" target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6
                rounded-lg text-lg font-semibold hover:bg-light hover:text-dark
                border-2 border-solid border-transparent hover:border-dark
                dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light max-md:p-2 max-md:px-4 max-md:text-base
                "
                  download={true}
                >Resume <LinkArrow className={"w-6 ml-1"} />

                </Link>
                <Link href="mailto:vaibhav.saini.professional@proton.me" target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light max-md:text-base"
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
      </main>
    </>
  )
}
